export const GET_REVENUE_SUCCESS = "GET_REVENUE_SUCCESS";
export const GET_REVENUE_FAIL = "GET_REVENUE_FAIL";
export const GET_REVENUE_DETAIL_SUCCESS = "GET_REVENUE_DETAIL_SUCCESS";
export const GET_REVENUE_DETAIL_FAIL = "GET_REVENUE_DETAIL_FAIL";
