export const GET_LIST_CONTACT_SUCCESS = "GET_LIST_CONTACT_SUCCESS";
export const GET_LIST_CONTACT_FAIL = "GET_LIST_CONTACT_FAIL";
export const GET_DETAIL_CONTACT_SUCCESS = "GET_DETAIL_CONTACT_SUCCESS";
export const GET_DETAIL_CONTACT_FAIL = "GET_DETAIL_CONTACT_FAIL";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";
