export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS";
export const GET_LIST_CATEGORY_FAIL = "GET_LIST_CATEGORY_FAIL";
export const GET_LIST_CATEGORY_NOT_PAG_SUCCESS =
  "GET_LIST_CATEGORY_NOT_PAG_SUCCESS";
export const GET_LIST_CATEGORY_NOT_PAG_FAIL = "GET_LIST_CATEGORY_NOT_PAG_FAIL";
export const GET_DETAIL_CATEGORY_SUCCESS = "GET_DETAIL_CATEGORY_SUCCESS";
export const GET_DETAIL_CATEGORY_FAIL = "GET_DETAIL_CATEGORY_FAIL";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
